require 'date'
require 'time'

module OpenapiClient
  # Invoice model
  class ModelInvoice
    # The invoice id. <span style='color:red'>Required</span> if you want to create or update an invoice position for an existing invoice
    attr_accessor :id

    # The invoice object name.
    attr_accessor :object_name

    # The invoice number
    attr_accessor :invoice_number

    attr_accessor :contact

    attr_accessor :contact_person

    # Date of invoice creation
    attr_accessor :create

    # Date of last invoice update
    attr_accessor :update

    attr_accessor :sev_client

    # Needs to be provided as timestamp or dd.mm.yyyy  **Requirements:** * For final invoices (invoiceType = 'ER'), the invoiceDate must be later than or equal to the invoiceDate of related advance (invoiceType = 'AR') / partial (invoiceType = 'TR') invoices.</li>
    attr_accessor :invoice_date

    # Normally consist of prefix plus the invoice number
    attr_accessor :header

    # Certain html tags can be used here to format your text
    attr_accessor :head_text

    # Certain html tags can be used here to format your text
    attr_accessor :foot_text

    # The time the customer has to pay the invoice in days
    attr_accessor :time_to_pay

    # If you want to give a discount, define the percentage here. Otherwise provide zero as value
    attr_accessor :discount

    # Complete address of the recipient including name, street, city, zip and country.       * Line breaks can be used and will be displayed on the invoice pdf.
    attr_accessor :address

    attr_accessor :address_country

    # Needs to be timestamp or dd.mm.yyyy
    attr_accessor :pay_date

    attr_accessor :create_user

    # Timestamp. This can also be a date range if you also use the attribute deliveryDateUntil
    attr_accessor :delivery_date

    # If the delivery date should be a time range, another timestamp can be provided in this attribute       * to define a range from timestamp used in deliveryDate attribute to the timestamp used here.
    attr_accessor :delivery_date_until

    # Please have a look in our       <a href='#tag/Invoice/Types-and-status-of-invoices'>Types and status of invoices</a>       to see what the different status codes mean
    attr_accessor :status

    # Defines if the client uses the small settlement scheme.      If yes, the invoice must not contain any vat
    attr_accessor :small_settlement

    # This is not used anymore. Use the taxRate of the individual positions instead.
    attr_accessor :tax_rate

    attr_accessor :tax_rule

    # A common tax text would be 'Umsatzsteuer 19%'
    attr_accessor :tax_text

    # **Use this in sevdesk-Update 1.0 (instead of taxRule).**  Tax type of the invoice. There are four tax types: 1. default - Umsatzsteuer ausweisen 2. eu - Steuerfreie innergemeinschaftliche Lieferung (Europäische Union) 3. noteu - Steuerschuldnerschaft des Leistungsempfängers (außerhalb EU, z. B. Schweiz) 4. custom - Using custom tax set 5. ss - Not subject to VAT according to §19 1 UStG Tax rates are heavily connected to the tax type used.
    attr_accessor :tax_type

    attr_accessor :tax_set

    # Defines how many reminders have already been sent for the invoice.      Starts with 1 (Payment reminder) and should be incremented by one every time another reminder is sent.
    attr_accessor :dunning_level

    attr_accessor :payment_method

    # The date the invoice was sent to the customer
    attr_accessor :send_date

    # Type of the invoice. For more information on the different types, check       <a href='#tag/Invoice/Types-and-status-of-invoices'>this</a> section  
    attr_accessor :invoice_type

    # The interval in which recurring invoices are due as ISO-8601 duration.<br>       Necessary attribute for all recurring invoices.
    attr_accessor :account_intervall

    # Timestamp when the next invoice will be generated by this recurring invoice.
    attr_accessor :account_next_invoice

    # Currency used in the invoice. Needs to be currency code according to ISO-4217
    attr_accessor :currency

    # Net sum of the invoice
    attr_accessor :sum_net

    # Tax sum of the invoice
    attr_accessor :sum_tax

    # Gross sum of the invoice
    attr_accessor :sum_gross

    # Sum of all discounts in the invoice
    attr_accessor :sum_discounts

    # Net sum of the invoice in the foreign currency
    attr_accessor :sum_net_foreign_currency

    # Tax sum of the invoice in the foreign currency
    attr_accessor :sum_tax_foreign_currency

    # Gross sum of the invoice in the foreign currency
    attr_accessor :sum_gross_foreign_currency

    # Discounts sum of the invoice in the foreign currency
    attr_accessor :sum_discounts_foreign_currency

    # Net accounting sum of the invoice. Is usually the same as sumNet
    attr_accessor :sum_net_accounting

    # Tax accounting sum of the invoice. Is usually the same as sumTax
    attr_accessor :sum_tax_accounting

    # Gross accounting sum of the invoice. Is usually the same as sumGross
    attr_accessor :sum_gross_accounting

    # Amount which has already been paid for this invoice by the customer
    attr_accessor :paid_amount

    # If true, the net amount of each position will be shown on the invoice. Otherwise gross amount
    attr_accessor :show_net

    # Enshrined invoices cannot be changed. Can only be set via [Invoice/{invoiceId}/enshrine](#tag/Invoice/operation/invoiceEnshrine). This operation cannot be undone.
    attr_accessor :enshrined

    # Type which was used to send the invoice.
    attr_accessor :send_type

    attr_accessor :origin

    # Internal note of the customer. Contains data entered into field 'Referenz/Bestellnummer'
    attr_accessor :customer_internal_note

    # If true, the invoice will be created as e-invoice.  To create a valid e-invoice some extra data are required - sevClient     - addressStreet     - addressZip     - addressCity     - bankIban     - bankBic     - contactEmail     - contactPhone     - taxNumber     - vatNumber - contact     - buyerReference     - email - invoice     - paymentMethod     - addressStreet     - addressZip     - addressCity     - addressCountry     - contact
    attr_accessor :property_is_e_invoice

    attr_accessor :map_all

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object_name' => :'objectName',
        :'invoice_number' => :'invoiceNumber',
        :'contact' => :'contact',
        :'contact_person' => :'contactPerson',
        :'create' => :'create',
        :'update' => :'update',
        :'sev_client' => :'sevClient',
        :'invoice_date' => :'invoiceDate',
        :'header' => :'header',
        :'head_text' => :'headText',
        :'foot_text' => :'footText',
        :'time_to_pay' => :'timeToPay',
        :'discount' => :'discount',
        :'address' => :'address',
        :'address_country' => :'addressCountry',
        :'pay_date' => :'payDate',
        :'create_user' => :'createUser',
        :'delivery_date' => :'deliveryDate',
        :'delivery_date_until' => :'deliveryDateUntil',
        :'status' => :'status',
        :'small_settlement' => :'smallSettlement',
        :'tax_rate' => :'taxRate',
        :'tax_rule' => :'taxRule',
        :'tax_text' => :'taxText',
        :'tax_type' => :'taxType',
        :'tax_set' => :'taxSet',
        :'dunning_level' => :'dunningLevel',
        :'payment_method' => :'paymentMethod',
        :'send_date' => :'sendDate',
        :'invoice_type' => :'invoiceType',
        :'account_intervall' => :'accountIntervall',
        :'account_next_invoice' => :'accountNextInvoice',
        :'currency' => :'currency',
        :'sum_net' => :'sumNet',
        :'sum_tax' => :'sumTax',
        :'sum_gross' => :'sumGross',
        :'sum_discounts' => :'sumDiscounts',
        :'sum_net_foreign_currency' => :'sumNetForeignCurrency',
        :'sum_tax_foreign_currency' => :'sumTaxForeignCurrency',
        :'sum_gross_foreign_currency' => :'sumGrossForeignCurrency',
        :'sum_discounts_foreign_currency' => :'sumDiscountsForeignCurrency',
        :'sum_net_accounting' => :'sumNetAccounting',
        :'sum_tax_accounting' => :'sumTaxAccounting',
        :'sum_gross_accounting' => :'sumGrossAccounting',
        :'paid_amount' => :'paidAmount',
        :'show_net' => :'showNet',
        :'enshrined' => :'enshrined',
        :'send_type' => :'sendType',
        :'origin' => :'origin',
        :'customer_internal_note' => :'customerInternalNote',
        :'property_is_e_invoice' => :'propertyIsEInvoice',
        :'map_all' => :'mapAll'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'object_name' => :'String',
        :'invoice_number' => :'String',
        :'contact' => :'ModelInvoiceContact',
        :'contact_person' => :'ModelInvoiceContactPerson',
        :'create' => :'Time',
        :'update' => :'Time',
        :'sev_client' => :'ModelInvoiceSevClient',
        :'invoice_date' => :'String',
        :'header' => :'String',
        :'head_text' => :'String',
        :'foot_text' => :'String',
        :'time_to_pay' => :'Integer',
        :'discount' => :'Integer',
        :'address' => :'String',
        :'address_country' => :'ModelInvoiceAddressCountry',
        :'pay_date' => :'Time',
        :'create_user' => :'ModelCreditNoteCreateUser',
        :'delivery_date' => :'Time',
        :'delivery_date_until' => :'Integer',
        :'status' => :'String',
        :'small_settlement' => :'Boolean',
        :'tax_rate' => :'Float',
        :'tax_rule' => :'ModelInvoiceResponseTaxRule',
        :'tax_text' => :'String',
        :'tax_type' => :'String',
        :'tax_set' => :'ModelInvoiceTaxSet',
        :'dunning_level' => :'Integer',
        :'payment_method' => :'ModelInvoicePaymentMethod',
        :'send_date' => :'Time',
        :'invoice_type' => :'String',
        :'account_intervall' => :'String',
        :'account_next_invoice' => :'Integer',
        :'currency' => :'String',
        :'sum_net' => :'Float',
        :'sum_tax' => :'Float',
        :'sum_gross' => :'Float',
        :'sum_discounts' => :'Float',
        :'sum_net_foreign_currency' => :'Float',
        :'sum_tax_foreign_currency' => :'Float',
        :'sum_gross_foreign_currency' => :'Float',
        :'sum_discounts_foreign_currency' => :'Float',
        :'sum_net_accounting' => :'Float',
        :'sum_tax_accounting' => :'Float',
        :'sum_gross_accounting' => :'Float',
        :'paid_amount' => :'Float',
        :'show_net' => :'Boolean',
        :'enshrined' => :'Time',
        :'send_type' => :'String',
        :'origin' => :'ModelInvoiceOrigin',
        :'customer_internal_note' => :'String',
        :'property_is_e_invoice' => :'Boolean',
        :'map_all' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'invoice_number',
        :'header',
        :'head_text',
        :'foot_text',
        :'time_to_pay',
        :'address',
        :'pay_date',
        :'delivery_date',
        :'delivery_date_until',
        :'small_settlement',
        :'tax_set',
        :'dunning_level',
        :'send_date',
        :'account_intervall',
        :'account_next_invoice',
        :'paid_amount',
        :'send_type',
        :'origin',
        :'customer_internal_note',
        :'property_is_e_invoice',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ModelInvoice` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ModelInvoice`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'object_name')
        self.object_name = attributes[:'object_name']
      end

      if attributes.key?(:'invoice_number')
        self.invoice_number = attributes[:'invoice_number']
      end

      if attributes.key?(:'contact')
        self.contact = attributes[:'contact']
      else
        self.contact = nil
      end

      if attributes.key?(:'contact_person')
        self.contact_person = attributes[:'contact_person']
      else
        self.contact_person = nil
      end

      if attributes.key?(:'create')
        self.create = attributes[:'create']
      end

      if attributes.key?(:'update')
        self.update = attributes[:'update']
      end

      if attributes.key?(:'sev_client')
        self.sev_client = attributes[:'sev_client']
      end

      if attributes.key?(:'invoice_date')
        self.invoice_date = attributes[:'invoice_date']
      else
        self.invoice_date = nil
      end

      if attributes.key?(:'header')
        self.header = attributes[:'header']
      end

      if attributes.key?(:'head_text')
        self.head_text = attributes[:'head_text']
      end

      if attributes.key?(:'foot_text')
        self.foot_text = attributes[:'foot_text']
      end

      if attributes.key?(:'time_to_pay')
        self.time_to_pay = attributes[:'time_to_pay']
      end

      if attributes.key?(:'discount')
        self.discount = attributes[:'discount']
      else
        self.discount = nil
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'address_country')
        self.address_country = attributes[:'address_country']
      else
        self.address_country = nil
      end

      if attributes.key?(:'pay_date')
        self.pay_date = attributes[:'pay_date']
      end

      if attributes.key?(:'create_user')
        self.create_user = attributes[:'create_user']
      end

      if attributes.key?(:'delivery_date')
        self.delivery_date = attributes[:'delivery_date']
      end

      if attributes.key?(:'delivery_date_until')
        self.delivery_date_until = attributes[:'delivery_date_until']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'small_settlement')
        self.small_settlement = attributes[:'small_settlement']
      end

      if attributes.key?(:'tax_rate')
        self.tax_rate = attributes[:'tax_rate']
      else
        self.tax_rate = nil
      end

      if attributes.key?(:'tax_rule')
        self.tax_rule = attributes[:'tax_rule']
      else
        self.tax_rule = nil
      end

      if attributes.key?(:'tax_text')
        self.tax_text = attributes[:'tax_text']
      else
        self.tax_text = nil
      end

      if attributes.key?(:'tax_type')
        self.tax_type = attributes[:'tax_type']
      else
        self.tax_type = nil
      end

      if attributes.key?(:'tax_set')
        self.tax_set = attributes[:'tax_set']
      end

      if attributes.key?(:'dunning_level')
        self.dunning_level = attributes[:'dunning_level']
      end

      if attributes.key?(:'payment_method')
        self.payment_method = attributes[:'payment_method']
      end

      if attributes.key?(:'send_date')
        self.send_date = attributes[:'send_date']
      end

      if attributes.key?(:'invoice_type')
        self.invoice_type = attributes[:'invoice_type']
      else
        self.invoice_type = nil
      end

      if attributes.key?(:'account_intervall')
        self.account_intervall = attributes[:'account_intervall']
      end

      if attributes.key?(:'account_next_invoice')
        self.account_next_invoice = attributes[:'account_next_invoice']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'sum_net')
        self.sum_net = attributes[:'sum_net']
      end

      if attributes.key?(:'sum_tax')
        self.sum_tax = attributes[:'sum_tax']
      end

      if attributes.key?(:'sum_gross')
        self.sum_gross = attributes[:'sum_gross']
      end

      if attributes.key?(:'sum_discounts')
        self.sum_discounts = attributes[:'sum_discounts']
      end

      if attributes.key?(:'sum_net_foreign_currency')
        self.sum_net_foreign_currency = attributes[:'sum_net_foreign_currency']
      end

      if attributes.key?(:'sum_tax_foreign_currency')
        self.sum_tax_foreign_currency = attributes[:'sum_tax_foreign_currency']
      end

      if attributes.key?(:'sum_gross_foreign_currency')
        self.sum_gross_foreign_currency = attributes[:'sum_gross_foreign_currency']
      end

      if attributes.key?(:'sum_discounts_foreign_currency')
        self.sum_discounts_foreign_currency = attributes[:'sum_discounts_foreign_currency']
      end

      if attributes.key?(:'sum_net_accounting')
        self.sum_net_accounting = attributes[:'sum_net_accounting']
      end

      if attributes.key?(:'sum_tax_accounting')
        self.sum_tax_accounting = attributes[:'sum_tax_accounting']
      end

      if attributes.key?(:'sum_gross_accounting')
        self.sum_gross_accounting = attributes[:'sum_gross_accounting']
      end

      if attributes.key?(:'paid_amount')
        self.paid_amount = attributes[:'paid_amount']
      end

      if attributes.key?(:'show_net')
        self.show_net = attributes[:'show_net']
      end

      if attributes.key?(:'enshrined')
        self.enshrined = attributes[:'enshrined']
      end

      if attributes.key?(:'send_type')
        self.send_type = attributes[:'send_type']
      end

      if attributes.key?(:'origin')
        self.origin = attributes[:'origin']
      end

      if attributes.key?(:'customer_internal_note')
        self.customer_internal_note = attributes[:'customer_internal_note']
      end

      if attributes.key?(:'property_is_e_invoice')
        self.property_is_e_invoice = attributes[:'property_is_e_invoice']
      end

      if attributes.key?(:'map_all')
        self.map_all = attributes[:'map_all']
      else
        self.map_all = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @contact.nil?
        invalid_properties.push('invalid value for "contact", contact cannot be nil.')
      end

      if @contact_person.nil?
        invalid_properties.push('invalid value for "contact_person", contact_person cannot be nil.')
      end

      if @invoice_date.nil?
        invalid_properties.push('invalid value for "invoice_date", invoice_date cannot be nil.')
      end

      if @discount.nil?
        invalid_properties.push('invalid value for "discount", discount cannot be nil.')
      end

      if @address_country.nil?
        invalid_properties.push('invalid value for "address_country", address_country cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @tax_rate.nil?
        invalid_properties.push('invalid value for "tax_rate", tax_rate cannot be nil.')
      end

      if @tax_rule.nil?
        invalid_properties.push('invalid value for "tax_rule", tax_rule cannot be nil.')
      end

      if @tax_text.nil?
        invalid_properties.push('invalid value for "tax_text", tax_text cannot be nil.')
      end

      if @tax_type.nil?
        invalid_properties.push('invalid value for "tax_type", tax_type cannot be nil.')
      end

      if @invoice_type.nil?
        invalid_properties.push('invalid value for "invoice_type", invoice_type cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @map_all.nil?
        invalid_properties.push('invalid value for "map_all", map_all cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @contact.nil?
      return false if @contact_person.nil?
      return false if @invoice_date.nil?
      return false if @discount.nil?
      return false if @address_country.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["50", "100", "200", "750", "1000"])
      return false unless status_validator.valid?(@status)
      return false if @tax_rate.nil?
      return false if @tax_rule.nil?
      return false if @tax_text.nil?
      return false if @tax_type.nil?
      tax_type_validator = EnumAttributeValidator.new('String', ["default", "eu", "noteu", "custom"])
      return false unless tax_type_validator.valid?(@tax_type)
      return false if @invoice_type.nil?
      invoice_type_validator = EnumAttributeValidator.new('String', ["RE", "WKR", "SR", "MA", "TR", "ER"])
      return false unless invoice_type_validator.valid?(@invoice_type)
      return false if @currency.nil?
      send_type_validator = EnumAttributeValidator.new('String', ["VPR", "VPDF", "VM", "VP"])
      return false unless send_type_validator.valid?(@send_type)
      return false if @map_all.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["50", "100", "200", "750", "1000"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tax_type Object to be assigned
    def tax_type=(tax_type)
      validator = EnumAttributeValidator.new('String', ["default", "eu", "noteu", "custom"])
      unless validator.valid?(tax_type)
        fail ArgumentError, "invalid value for \"tax_type\", must be one of #{validator.allowable_values}."
      end
      @tax_type = tax_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] invoice_type Object to be assigned
    def invoice_type=(invoice_type)
      validator = EnumAttributeValidator.new('String', ["RE", "WKR", "SR", "MA", "TR", "ER"])
      unless validator.valid?(invoice_type)
        fail ArgumentError, "invalid value for \"invoice_type\", must be one of #{validator.allowable_values}."
      end
      @invoice_type = invoice_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] send_type Object to be assigned
    def send_type=(send_type)
      validator = EnumAttributeValidator.new('String', ["VPR", "VPDF", "VM", "VP"])
      unless validator.valid?(send_type)
        fail ArgumentError, "invalid value for \"send_type\", must be one of #{validator.allowable_values}."
      end
      @send_type = send_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object_name == o.object_name &&
          invoice_number == o.invoice_number &&
          contact == o.contact &&
          contact_person == o.contact_person &&
          create == o.create &&
          update == o.update &&
          sev_client == o.sev_client &&
          invoice_date == o.invoice_date &&
          header == o.header &&
          head_text == o.head_text &&
          foot_text == o.foot_text &&
          time_to_pay == o.time_to_pay &&
          discount == o.discount &&
          address == o.address &&
          address_country == o.address_country &&
          pay_date == o.pay_date &&
          create_user == o.create_user &&
          delivery_date == o.delivery_date &&
          delivery_date_until == o.delivery_date_until &&
          status == o.status &&
          small_settlement == o.small_settlement &&
          tax_rate == o.tax_rate &&
          tax_rule == o.tax_rule &&
          tax_text == o.tax_text &&
          tax_type == o.tax_type &&
          tax_set == o.tax_set &&
          dunning_level == o.dunning_level &&
          payment_method == o.payment_method &&
          send_date == o.send_date &&
          invoice_type == o.invoice_type &&
          account_intervall == o.account_intervall &&
          account_next_invoice == o.account_next_invoice &&
          currency == o.currency &&
          sum_net == o.sum_net &&
          sum_tax == o.sum_tax &&
          sum_gross == o.sum_gross &&
          sum_discounts == o.sum_discounts &&
          sum_net_foreign_currency == o.sum_net_foreign_currency &&
          sum_tax_foreign_currency == o.sum_tax_foreign_currency &&
          sum_gross_foreign_currency == o.sum_gross_foreign_currency &&
          sum_discounts_foreign_currency == o.sum_discounts_foreign_currency &&
          sum_net_accounting == o.sum_net_accounting &&
          sum_tax_accounting == o.sum_tax_accounting &&
          sum_gross_accounting == o.sum_gross_accounting &&
          paid_amount == o.paid_amount &&
          show_net == o.show_net &&
          enshrined == o.enshrined &&
          send_type == o.send_type &&
          origin == o.origin &&
          customer_internal_note == o.customer_internal_note &&
          property_is_e_invoice == o.property_is_e_invoice &&
          map_all == o.map_all
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object_name, invoice_number, contact, contact_person, create, update, sev_client, invoice_date, header, head_text, foot_text, time_to_pay, discount, address, address_country, pay_date, create_user, delivery_date, delivery_date_until, status, small_settlement, tax_rate, tax_rule, tax_text, tax_type, tax_set, dunning_level, payment_method, send_date, invoice_type, account_intervall, account_next_invoice, currency, sum_net, sum_tax, sum_gross, sum_discounts, sum_net_foreign_currency, sum_tax_foreign_currency, sum_gross_foreign_currency, sum_discounts_foreign_currency, sum_net_accounting, sum_tax_accounting, sum_gross_accounting, paid_amount, show_net, enshrined, send_type, origin, customer_internal_note, property_is_e_invoice, map_all].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
