require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::BasicsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BasicsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::BasicsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BasicsApi' do
    it 'should create an instance of BasicsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::BasicsApi)
    end
  end

  # unit tests for bookkeeping_system_version
  # Retrieve bookkeeping system version
  # To check if you already received the update to version 2.0 you can use this endpoint.
  # @param [Hash] opts the optional parameters
  # @return [BookkeepingSystemVersion200Response]
  describe 'bookkeeping_system_version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
