require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CheckAccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckAccountApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CheckAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckAccountApi' do
    it 'should create an instance of CheckAccountApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CheckAccountApi)
    end
  end

  # unit tests for create_clearing_account
  # Create a new clearing account
  # Creates a new clearing account.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateClearingAccount] :create_clearing_account Data to create a clearning account
  # @return [CreateClearingAccount201Response]
  describe 'create_clearing_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_file_import_account
  # Create a new file import account
  # Creates a new banking account for file imports (CSV, MT940).
  # @param [Hash] opts the optional parameters
  # @option opts [CreateFileImportAccount] :create_file_import_account Data to create a file import account
  # @return [CreateFileImportAccount201Response]
  describe 'create_file_import_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_check_account
  # Deletes a check account
  # @param check_account_id Id of check account to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteCheckAccount200Response]
  describe 'delete_check_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_balance_at_date
  # Get the balance at a given date
  # Get the balance, calculated as the sum of all transactions sevdesk knows, up to and including the given date. Note that this balance does not have to be the actual bank account balance, e.g. if sevdesk did not import old transactions.
  # @param check_account_id ID of check account
  # @param date Only consider transactions up to this date at 23:59:59
  # @param [Hash] opts the optional parameters
  # @return [GetBalanceAtDate200Response]
  describe 'get_balance_at_date test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_check_account_by_id
  # Find check account by ID
  # Retrieve an existing check account
  # @param check_account_id ID of check account
  # @param [Hash] opts the optional parameters
  # @return [GetCheckAccounts200Response]
  describe 'get_check_account_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_check_accounts
  # Retrieve check accounts
  # Retrieve all check accounts
  # @param [Hash] opts the optional parameters
  # @return [GetCheckAccounts200Response]
  describe 'get_check_accounts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_check_account
  # Update an existing check account
  # Update a check account
  # @param check_account_id ID of check account to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelCheckAccountUpdate] :model_check_account_update Update data
  # @return [ModelCheckAccountResponse]
  describe 'update_check_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
