require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CommunicationWayApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CommunicationWayApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CommunicationWayApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommunicationWayApi' do
    it 'should create an instance of CommunicationWayApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CommunicationWayApi)
    end
  end

  # unit tests for create_communication_way
  # Create a new contact communication way
  # Creates a new contact communication way.
  # @param [Hash] opts the optional parameters
  # @option opts [ModelCommunicationWay] :model_communication_way Creation data
  # @return [ModelCommunicationWayResponse]
  describe 'create_communication_way test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_communication_way
  # Deletes a communication way
  # @param communication_way_id Id of communication way resource to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteCheckAccount200Response]
  describe 'delete_communication_way test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_communication_way_by_id
  # Find communication way by ID
  # Returns a single communication way
  # @param communication_way_id ID of communication way to return
  # @param [Hash] opts the optional parameters
  # @return [GetCommunicationWays200Response]
  describe 'get_communication_way_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_communication_way_keys
  # Retrieve communication way keys
  # Returns all communication way keys.
  # @param [Hash] opts the optional parameters
  # @return [GetCommunicationWayKeys200Response]
  describe 'get_communication_way_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_communication_ways
  # Retrieve communication ways
  # Returns all communication ways which have been added up until now. Filters can be added.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :contact_id ID of contact for which you want the communication ways.
  # @option opts [String] :contact_object_name Object name. Only needed if you also defined the ID of a contact.
  # @option opts [String] :type Type of the communication ways you want to get.
  # @option opts [String] :main Define if you only want the main communication way.
  # @return [GetCommunicationWays200Response]
  describe 'get_communication_ways test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_communication_way
  # Update a existing communication way
  # Update a communication way
  # @param communication_way_id ID of CommunicationWay to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelCommunicationWayUpdate] :model_communication_way_update Update data
  # @return [ModelCommunicationWayResponse]
  describe 'update_communication_way test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
