require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ContactAddressApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactAddressApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ContactAddressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactAddressApi' do
    it 'should create an instance of ContactAddressApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ContactAddressApi)
    end
  end

  # unit tests for contact_address_id
  # Find contact address by ID
  # Returns a single contact address
  # @param contact_address_id ID of contact address to return
  # @param [Hash] opts the optional parameters
  # @return [GetContactAddresses200Response]
  describe 'contact_address_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_contact_address
  # Create a new contact address
  # Creates a new contact address.
  # @param [Hash] opts the optional parameters
  # @option opts [ModelContactAddress] :model_contact_address Creation data
  # @return [ModelContactAddressResponse]
  describe 'create_contact_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_contact_address
  # Deletes a contact address
  # @param contact_address_id Id of contact address resource to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteCheckAccount200Response]
  describe 'delete_contact_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact_addresses
  # Retrieve contact addresses
  # Retrieve all contact addresses
  # @param [Hash] opts the optional parameters
  # @return [GetContactAddresses200Response]
  describe 'get_contact_addresses test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_contact_address
  # update a existing contact address
  # update a existing contact address.
  # @param contact_address_id ID of contact address to return
  # @param [Hash] opts the optional parameters
  # @option opts [ModelContactAddressUpdate] :model_contact_address_update Creation data
  # @return [ModelContactAddressResponse]
  describe 'update_contact_address test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
