require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::InvoicePosApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvoicePosApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::InvoicePosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvoicePosApi' do
    it 'should create an instance of InvoicePosApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::InvoicePosApi)
    end
  end

  # unit tests for get_invoice_pos
  # Retrieve InvoicePos
  # There are a multitude of parameter which can be used to filter.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :id Retrieve all InvoicePos with this InvoicePos id
  # @option opts [Float] :invoice_id Retrieve all invoices positions with this invoice. Must be provided with invoice[objectName]
  # @option opts [String] :invoice_object_name Only required if invoice[id] was provided. &#39;Invoice&#39; should be used as value.
  # @option opts [Float] :part_id Retrieve all invoices positions with this part. Must be provided with part[objectName]
  # @option opts [String] :part_object_name Only required if part[id] was provided. &#39;Part&#39; should be used as value.
  # @return [GetInvoicePositionsById200Response]
  describe 'get_invoice_pos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
