require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LayoutApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LayoutApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LayoutApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LayoutApi' do
    it 'should create an instance of LayoutApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LayoutApi)
    end
  end

  # unit tests for get_letterpapers_with_thumb
  # Retrieve letterpapers
  # Retrieve all letterpapers with Thumb
  # @param [Hash] opts the optional parameters
  # @return [GetLetterpapersWithThumb200Response]
  describe 'get_letterpapers_with_thumb test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_templates
  # Retrieve templates
  # Retrieve all templates
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type Type of the templates you want to get.
  # @return [GetTemplates200Response]
  describe 'get_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_credit_note_template
  # Update an of credit note template
  # Update an existing of credit note template
  # @param credit_note_id ID of credit note to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelChangeLayout] :model_change_layout Change Layout
  # @return [ModelChangeLayoutResponse]
  describe 'update_credit_note_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_invoice_template
  # Update an invoice template
  # Update an existing invoice template
  # @param invoice_id ID of invoice to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelChangeLayout] :model_change_layout Change Layout
  # @return [ModelChangeLayoutResponse]
  describe 'update_invoice_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_order_template
  # Update an order template
  # Update an existing order template
  # @param order_id ID of order to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelChangeLayout] :model_change_layout Change Layout
  # @return [ModelChangeLayoutResponse]
  describe 'update_order_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
