require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::OrderPosApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderPosApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::OrderPosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderPosApi' do
    it 'should create an instance of OrderPosApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::OrderPosApi)
    end
  end

  # unit tests for delete_order_pos
  # Deletes an order Position
  # @param order_pos_id Id of order position resource to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteCheckAccount200Response]
  describe 'delete_order_pos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_order_position_by_id
  # Find order position by ID
  # Returns a single order position
  # @param order_pos_id ID of order position to return
  # @param [Hash] opts the optional parameters
  # @return [GetOrderPositionsById200Response]
  describe 'get_order_position_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_order_positions
  # Retrieve order positions
  # Retrieve all order positions depending on the filters defined in the query.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :order_id Retrieve all order positions belonging to this order. Must be provided with voucher[objectName]
  # @option opts [String] :order_object_name Only required if order[id] was provided. &#39;Order&#39; should be used as value.
  # @return [GetOrderPositionsById200Response]
  describe 'get_order_positions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_order_position
  # Update an existing order position
  # Update an order position
  # @param order_pos_id ID of order position to update
  # @param [Hash] opts the optional parameters
  # @option opts [ModelOrderPosUpdate] :model_order_pos_update Update data
  # @return [ModelOrderPosResponse]
  describe 'update_order_position test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
