require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ReportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReportApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ReportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportApi' do
    it 'should create an instance of ReportApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ReportApi)
    end
  end

  # unit tests for report_contact
  # Export contact list
  # Export contact list
  # @param sev_query 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :download 
  # @return [ReportContact200Response]
  describe 'report_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for report_invoice
  # Export invoice list
  # Export invoice list
  # @param view 
  # @param sev_query 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :download 
  # @return [ReportInvoice200Response]
  describe 'report_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for report_order
  # Export order list
  # Export order list
  # @param view 
  # @param sev_query 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :download 
  # @return [ReportOrder200Response]
  describe 'report_order test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for report_voucher
  # Export voucher list
  # Export voucher list
  # @param sev_query 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :download 
  # @return [ReportVoucher200Response]
  describe 'report_voucher test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
