require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::BookkeepingSystemVersion200ResponseObjects
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::BookkeepingSystemVersion200ResponseObjects do
  let(:instance) { OpenapiClient::BookkeepingSystemVersion200ResponseObjects.new }

  describe 'test an instance of BookkeepingSystemVersion200ResponseObjects' do
    it 'should create an instance of BookkeepingSystemVersion200ResponseObjects' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::BookkeepingSystemVersion200ResponseObjects)
    end
  end

  describe 'test attribute "version"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["1.0", "2.0"])
      # validator.allowable_values.each do |value|
      #   expect { instance.version = value }.not_to raise_error
      # end
    end
  end

end
