require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateTagRequestObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateTagRequestObject do
  let(:instance) { OpenapiClient::CreateTagRequestObject.new }

  describe 'test an instance of CreateTagRequestObject' do
    it 'should create an instance of CreateTagRequestObject' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateTagRequestObject)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "object_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Invoice", "Voucher", "Order", "CreditNote"])
      # validator.allowable_values.each do |value|
      #   expect { instance.object_name = value }.not_to raise_error
      # end
    end
  end

end
