require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateFileImportAccount
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateFileImportAccount do
  let(:instance) { OpenapiClient::CreateFileImportAccount.new }

  describe 'test an instance of CreateFileImportAccount' do
    it 'should create an instance of CreateFileImportAccount' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateFileImportAccount)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "import_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["CSV", "MT940"])
      # validator.allowable_values.each do |value|
      #   expect { instance.import_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "accounting_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "iban"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
