require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateCreditNoteFromInvoice201ResponseObjects
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateCreditNoteFromInvoice201ResponseObjects do
  let(:instance) { OpenapiClient::CreateCreditNoteFromInvoice201ResponseObjects.new }

  describe 'test an instance of CreateCreditNoteFromInvoice201ResponseObjects' do
    it 'should create an instance of CreateCreditNoteFromInvoice201ResponseObjects' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateCreditNoteFromInvoice201ResponseObjects)
    end
  end

  describe 'test attribute "credit_note"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "credit_note_pos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "discount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
