require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateCreditNoteFromVoucherRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateCreditNoteFromVoucherRequest do
  let(:instance) { OpenapiClient::CreateCreditNoteFromVoucherRequest.new }

  describe 'test an instance of CreateCreditNoteFromVoucherRequest' do
    it 'should create an instance of CreateCreditNoteFromVoucherRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateCreditNoteFromVoucherRequest)
    end
  end

  describe 'test attribute "voucher"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
