require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateInvoiceReminderRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateInvoiceReminderRequest do
  let(:instance) { OpenapiClient::CreateInvoiceReminderRequest.new }

  describe 'test an instance of CreateInvoiceReminderRequest' do
    it 'should create an instance of CreateInvoiceReminderRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateInvoiceReminderRequest)
    end
  end

  describe 'test attribute "invoice"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
