require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateCreditNoteFromInvoiceRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateCreditNoteFromInvoiceRequest do
  let(:instance) { OpenapiClient::CreateCreditNoteFromInvoiceRequest.new }

  describe 'test an instance of CreateCreditNoteFromInvoiceRequest' do
    it 'should create an instance of CreateCreditNoteFromInvoiceRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreateCreditNoteFromInvoiceRequest)
    end
  end

  describe 'test attribute "invoice"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
