require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreditNoteGetPdf200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreditNoteGetPdf200Response do
  let(:instance) { OpenapiClient::CreditNoteGetPdf200Response.new }

  describe 'test an instance of CreditNoteGetPdf200Response' do
    it 'should create an instance of CreditNoteGetPdf200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::CreditNoteGetPdf200Response)
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mime_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "base64encoded"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
