require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportTransactionsSevQueryParameterFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportTransactionsSevQueryParameterFilter do
  let(:instance) { OpenapiClient::ExportTransactionsSevQueryParameterFilter.new }

  describe 'test an instance of ExportTransactionsSevQueryParameterFilter' do
    it 'should create an instance of ExportTransactionsSevQueryParameterFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportTransactionsSevQueryParameterFilter)
    end
  end

  describe 'test attribute "paymt_purpose"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "check_account"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
