require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportInvoiceSevQueryParameterFilterContact
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportInvoiceSevQueryParameterFilterContact do
  let(:instance) { OpenapiClient::ExportInvoiceSevQueryParameterFilterContact.new }

  describe 'test an instance of ExportInvoiceSevQueryParameterFilterContact' do
    it 'should create an instance of ExportInvoiceSevQueryParameterFilterContact' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportInvoiceSevQueryParameterFilterContact)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "object_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
