require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportVoucherSevQueryParameter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportVoucherSevQueryParameter do
  let(:instance) { OpenapiClient::ExportVoucherSevQueryParameter.new }

  describe 'test an instance of ExportVoucherSevQueryParameter' do
    it 'should create an instance of ExportVoucherSevQueryParameter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportVoucherSevQueryParameter)
    end
  end

  describe 'test attribute "limit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "model_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "object_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filter"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
