require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportInvoiceSevQueryParameterFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportInvoiceSevQueryParameterFilter do
  let(:instance) { OpenapiClient::ExportInvoiceSevQueryParameterFilter.new }

  describe 'test an instance of ExportInvoiceSevQueryParameterFilter' do
    it 'should create an instance of ExportInvoiceSevQueryParameterFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportInvoiceSevQueryParameterFilter)
    end
  end

  describe 'test attribute "invoice_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["Re", "SR", "TR", "AR", "ER", "WKR", "MA"])
      # validator.allowable_values.each do |value|
      #   expect { instance.invoice_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "start_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "contact"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
