require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportContactSevQueryParameterFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportContactSevQueryParameterFilter do
  let(:instance) { OpenapiClient::ExportContactSevQueryParameterFilter.new }

  describe 'test an instance of ExportContactSevQueryParameterFilter' do
    it 'should create an instance of ExportContactSevQueryParameterFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportContactSevQueryParameterFilter)
    end
  end

  describe 'test attribute "zip"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "city"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "country"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "depth"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "only_people"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
