require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ExportTransactions200ResponseObjects
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ExportTransactions200ResponseObjects do
  let(:instance) { OpenapiClient::ExportTransactions200ResponseObjects.new }

  describe 'test an instance of ExportTransactions200ResponseObjects' do
    it 'should create an instance of ExportTransactions200ResponseObjects' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ExportTransactions200ResponseObjects)
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mimetype"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "base64_encoded"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
