require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetBalanceAtDate200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetBalanceAtDate200Response do
  let(:instance) { OpenapiClient::GetBalanceAtDate200Response.new }

  describe 'test an instance of GetBalanceAtDate200Response' do
    it 'should create an instance of GetBalanceAtDate200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::GetBalanceAtDate200Response)
    end
  end

  describe 'test attribute "objects"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
