require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetLetterpapersWithThumb200ResponseLetterpapersInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetLetterpapersWithThumb200ResponseLetterpapersInner do
  let(:instance) { OpenapiClient::GetLetterpapersWithThumb200ResponseLetterpapersInner.new }

  describe 'test an instance of GetLetterpapersWithThumb200ResponseLetterpapersInner' do
    it 'should create an instance of GetLetterpapersWithThumb200ResponseLetterpapersInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::GetLetterpapersWithThumb200ResponseLetterpapersInner)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pdf"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "sev_client"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "default"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "img"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
