require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InvoiceRender201ResponseParametersInnerValuesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::InvoiceRender201ResponseParametersInnerValuesInner do
  let(:instance) { OpenapiClient::InvoiceRender201ResponseParametersInnerValuesInner.new }

  describe 'test an instance of InvoiceRender201ResponseParametersInnerValuesInner' do
    it 'should create an instance of InvoiceRender201ResponseParametersInnerValuesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::InvoiceRender201ResponseParametersInnerValuesInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "translation_cade"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
