require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InvoiceRenderRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::InvoiceRenderRequest do
  let(:instance) { OpenapiClient::InvoiceRenderRequest.new }

  describe 'test an instance of InvoiceRenderRequest' do
    it 'should create an instance of InvoiceRenderRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::InvoiceRenderRequest)
    end
  end

  describe 'test attribute "force_reload"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
