require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelAccountingContactUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelAccountingContactUpdate do
  let(:instance) { OpenapiClient::ModelAccountingContactUpdate.new }

  describe 'test an instance of ModelAccountingContactUpdate' do
    it 'should create an instance of ModelAccountingContactUpdate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelAccountingContactUpdate)
    end
  end

  describe 'test attribute "contact"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "debitor_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "creditor_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
