require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelChangeLayout
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelChangeLayout do
  let(:instance) { OpenapiClient::ModelChangeLayout.new }

  describe 'test an instance of ModelChangeLayout' do
    it 'should create an instance of ModelChangeLayout' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelChangeLayout)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["language", "template", "letterpaper", "payPal"])
      # validator.allowable_values.each do |value|
      #   expect { instance.key = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
