require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner do
  let(:instance) { OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner.new }

  describe 'test an instance of ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner' do
    it 'should create an instance of ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInnerValuesInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "translation_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
