require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelChangeLayoutResponseMetadaten
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelChangeLayoutResponseMetadaten do
  let(:instance) { OpenapiClient::ModelChangeLayoutResponseMetadaten.new }

  describe 'test an instance of ModelChangeLayoutResponseMetadaten' do
    it 'should create an instance of ModelChangeLayoutResponseMetadaten' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelChangeLayoutResponseMetadaten)
    end
  end

  describe 'test attribute "pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "doc_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "thumbs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
