require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelChangeLayoutResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelChangeLayoutResponse do
  let(:instance) { OpenapiClient::ModelChangeLayoutResponse.new }

  describe 'test an instance of ModelChangeLayoutResponse' do
    it 'should create an instance of ModelChangeLayoutResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelChangeLayoutResponse)
    end
  end

  describe 'test attribute "result"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "metadaten"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
