require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInner do
  let(:instance) { OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInner.new }

  describe 'test an instance of ModelChangeLayoutResponseMetadatenThumbsInner' do
    it 'should create an instance of ModelChangeLayoutResponseMetadatenThumbsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelChangeLayoutResponseMetadatenThumbsInner)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "values"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
