require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelCreateInvoiceFromOrder
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelCreateInvoiceFromOrder do
  let(:instance) { OpenapiClient::ModelCreateInvoiceFromOrder.new }

  describe 'test an instance of ModelCreateInvoiceFromOrder' do
    it 'should create an instance of ModelCreateInvoiceFromOrder' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelCreateInvoiceFromOrder)
    end
  end

  describe 'test attribute "order"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["percentage", "net", "gross"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "partial_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["RE", "TR", "AR"])
      # validator.allowable_values.each do |value|
      #   expect { instance.partial_type = value }.not_to raise_error
      # end
    end
  end

end
