require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelContactCustomFieldUpdate
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelContactCustomFieldUpdate do
  let(:instance) { OpenapiClient::ModelContactCustomFieldUpdate.new }

  describe 'test an instance of ModelContactCustomFieldUpdate' do
    it 'should create an instance of ModelContactCustomFieldUpdate' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelContactCustomFieldUpdate)
    end
  end

  describe 'test attribute "contact"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "contact_custom_field_setting"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "object_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
