require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner do
  let(:instance) { OpenapiClient::ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner.new }

  describe 'test an instance of ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner' do
    it 'should create an instance of ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ModelTextparserFetchDictionaryEntriesByTypeResponseValueInner)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
