require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ReceiptGuideDtoAllowedTaxRulesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ReceiptGuideDtoAllowedTaxRulesInner do
  let(:instance) { OpenapiClient::ReceiptGuideDtoAllowedTaxRulesInner.new }

  describe 'test an instance of ReceiptGuideDtoAllowedTaxRulesInner' do
    it 'should create an instance of ReceiptGuideDtoAllowedTaxRulesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ReceiptGuideDtoAllowedTaxRulesInner)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "tax_rates"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
