require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ReportOrderSevQueryParameterFilter
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ReportOrderSevQueryParameterFilter do
  let(:instance) { OpenapiClient::ReportOrderSevQueryParameterFilter.new }

  describe 'test an instance of ReportOrderSevQueryParameterFilter' do
    it 'should create an instance of ReportOrderSevQueryParameterFilter' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ReportOrderSevQueryParameterFilter)
    end
  end

  describe 'test attribute "order_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["AN", "AB", "LI"])
      # validator.allowable_values.each do |value|
      #   expect { instance.order_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "start_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "contact"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "start_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "end_amount"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
