require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveVoucher
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveVoucher do
  let(:instance) { OpenapiClient::SaveVoucher.new }

  describe 'test an instance of SaveVoucher' do
    it 'should create an instance of SaveVoucher' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveVoucher)
    end
  end

  describe 'test attribute "voucher"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "voucher_pos_save"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "voucher_pos_delete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
