require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveInvoiceDiscountDelete
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveInvoiceDiscountDelete do
  let(:instance) { OpenapiClient::SaveInvoiceDiscountDelete.new }

  describe 'test an instance of SaveInvoiceDiscountDelete' do
    it 'should create an instance of SaveInvoiceDiscountDelete' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveInvoiceDiscountDelete)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "object_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
