require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveCreditNote
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveCreditNote do
  let(:instance) { OpenapiClient::SaveCreditNote.new }

  describe 'test an instance of SaveCreditNote' do
    it 'should create an instance of SaveCreditNote' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveCreditNote)
    end
  end

  describe 'test attribute "credit_note"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "credit_note_pos_save"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "credit_note_pos_delete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "discount_save"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "discount_delete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
