require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveInvoiceResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveInvoiceResponse do
  let(:instance) { OpenapiClient::SaveInvoiceResponse.new }

  describe 'test an instance of SaveInvoiceResponse' do
    it 'should create an instance of SaveInvoiceResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveInvoiceResponse)
    end
  end

  describe 'test attribute "invoice"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "invoice_pos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
