require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveOrderResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveOrderResponse do
  let(:instance) { OpenapiClient::SaveOrderResponse.new }

  describe 'test an instance of SaveOrderResponse' do
    it 'should create an instance of SaveOrderResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveOrderResponse)
    end
  end

  describe 'test attribute "order"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "order_pos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
