require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveVoucherResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveVoucherResponse do
  let(:instance) { OpenapiClient::SaveVoucherResponse.new }

  describe 'test an instance of SaveVoucherResponse' do
    it 'should create an instance of SaveVoucherResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveVoucherResponse)
    end
  end

  describe 'test attribute "voucher"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "voucher_pos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
