require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::SaveCreditNoteResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::SaveCreditNoteResponse do
  let(:instance) { OpenapiClient::SaveCreditNoteResponse.new }

  describe 'test an instance of SaveCreditNoteResponse' do
    it 'should create an instance of SaveCreditNoteResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::SaveCreditNoteResponse)
    end
  end

  describe 'test attribute "credit_note"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "credit_note_pos"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
