require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::UpdateExportConfigRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::UpdateExportConfigRequest do
  let(:instance) { OpenapiClient::UpdateExportConfigRequest.new }

  describe 'test an instance of UpdateExportConfigRequest' do
    it 'should create an instance of UpdateExportConfigRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::UpdateExportConfigRequest)
    end
  end

  describe 'test attribute "accountant_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "accountant_client_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "accounting_year_begin"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
