require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::UpdateTagRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::UpdateTagRequest do
  let(:instance) { OpenapiClient::UpdateTagRequest.new }

  describe 'test an instance of UpdateTagRequest' do
    it 'should create an instance of UpdateTagRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::UpdateTagRequest)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
