require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ValidationErrorError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ValidationErrorError do
  let(:instance) { OpenapiClient::ValidationErrorError.new }

  describe 'test an instance of ValidationErrorError' do
    it 'should create an instance of ValidationErrorError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ValidationErrorError)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "exception_uuid"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
