require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::VoucherUploadFile201ResponseObjects
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::VoucherUploadFile201ResponseObjects do
  let(:instance) { OpenapiClient::VoucherUploadFile201ResponseObjects.new }

  describe 'test an instance of VoucherUploadFile201ResponseObjects' do
    it 'should create an instance of VoucherUploadFile201ResponseObjects' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::VoucherUploadFile201ResponseObjects)
    end
  end

  describe 'test attribute "pages"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mime_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "origin_mime_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "content_hash"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
