require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::VoucherUploadFileRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::VoucherUploadFileRequest do
  let(:instance) { OpenapiClient::VoucherUploadFileRequest.new }

  describe 'test an instance of VoucherUploadFileRequest' do
    it 'should create an instance of VoucherUploadFileRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::VoucherUploadFileRequest)
    end
  end

  describe 'test attribute "file"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
